- name: add epel
  yum : name=epel-release

- name: change repositories option
  replace : dest=/etc/yum.repos.d/epel.repo regexp="enabled *= *1" replace="enabled=0"

- name: add remi
  yum : name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: install php
  yum:
    name: "{{ item }}"
    enablerepo: remi-php71
    state: latest
  with_items:
    - php
    - php-cli
    - php-common
    - php-fpm
    - php-devel
    - php-mbstring
    - php-pdo
    - php-gd

- name: is composer installed 
  stat:
    path: /usr/bin/composer
  register: composer

- name: install composer
  shell: "{{ item  }}" 
  args:
    chdir: /usr/bin
  with_items:
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar composer
  when: not composer.stat.exists

