# 最新のgitをインストール

- name: add IUS repository
  yum_repository:
    name: ius
    description: IUS YUM repo for install the latest git 
    baseurl: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64
    # https://access.redhat.com/documentation/ja-JP/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Security_Guide-Updating_Packages-Verifying_Signed_Packages.html
    gpgkey: https://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY
    gpgcheck: yes

- name: install git
  yum:
    name: git2u 
    enablerepo: ius
    state: present

- shell: git --version
  register: result
  changed_when: False
- debug: var=result.stdout
